### ISSUE TITLE
Change line 11 script/download.sh

### ISSUE THREAD

**Issue by NoeRzPz** [NoeRzPz/decont#1]
Hola Tomás,
Escribo porque envié el entregable y lo cancelé varias veces porque me di cuenta de que tenía fallos en los comentarios. Pensaba que había terminado pero creo que podría mejorar y hacer más generalizable la condicional de la línea 11 de download.sh con esta expresión:

`if [ $(ls $out_dir/*.fastq.gz | wc -l) -eq $(cat $file_url | wc -l) ]; then
      echo "File $file_url already downloaded"
      exit 0; fi`
De esta forma ya no necesitaría la variable de la línea 6. Mi pregunta es, ¿tendría que volver a cancelar la entrega ?  O como la entrega es solo la dirección de github no haría falta y  solo tendría que cambiar el código?

Muchas gracias,
Noelia

**Comment by tdido** [comment]
No te preocupes, la entrega es sólo para tener registro de las URL de los repos.

**Comment by NoeRzPz** [comment]
Muchas gracias, perdona por haberla cancelado antes.
